"""Report generation utilities."""

import logging
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Dict, Any

from config import Config

try:
    from .pdf_exporter import PDFExporter
    PDF_EXPORT_AVAILABLE = True
except ImportError:
    PDF_EXPORT_AVAILABLE = False
    PDFExporter = None

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generate analysis reports in various formats."""

    def __init__(self, config: Optional[Config] = None):
        """Initialize report generator.

        Args:
            config: Configuration object.
        """
        self.config = config or Config()

    def generate(
        self,
        results: List[Any],  # List[AnalysisResult]
        output_path: Optional[Path] = None,
        title: str = "Vision Agent Analysis Report",
        include_metadata: bool = True,
        **kwargs
    ) -> Path:
        """Generate a report from analysis results.

        Args:
            results: List of AnalysisResult objects.
            output_path: Optional output path. If None, auto-generates.
            title: Report title.
            include_metadata: Whether to include metadata in the report.
            **kwargs: Additional parameters.

        Returns:
            Path to the generated report file.
        """
        if not results:
            logger.warning("No results to generate report from")
            return None

        # Auto-generate output path if not provided
        if output_path is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = self.config.output_dir / f"report_{timestamp}.md"
        else:
            output_path = Path(output_path)

        output_path.parent.mkdir(parents=True, exist_ok=True)

        logger.info(f"Generating report: {output_path}")

        # Generate markdown report
        content = self._generate_markdown(
            results=results,
            title=title,
            include_metadata=include_metadata,
            **kwargs
        )

        # Write to file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        logger.info(f"Report generated successfully: {output_path}")
        return output_path

    def _generate_markdown(
        self,
        results: List[Any],
        title: str,
        include_metadata: bool = True,
        **kwargs
    ) -> str:
        """Generate markdown report content.

        Args:
            results: List of AnalysisResult objects.
            title: Report title.
            include_metadata: Whether to include metadata.
            **kwargs: Additional parameters.

        Returns:
            Markdown content as string.
        """
        lines = []

        # Title
        lines.append(f"# {title}\n")

        # Metadata
        if include_metadata:
            lines.append("## Report Information\n")
            lines.append(f"- **Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            lines.append(f"- **Model**: {self.config.ollama_model}")
            lines.append(f"- **Total Files Analyzed**: {len(results)}")
            lines.append("")

        # Table of Contents
        lines.append("## Table of Contents\n")
        for idx, result in enumerate(results, 1):
            file_name = result.file_path.name
            anchor = self._create_anchor(file_name, idx)
            lines.append(f"{idx}. [{file_name}](#{anchor})")
        lines.append("")

        # Analysis Results
        lines.append("---\n")
        lines.append("## Analysis Results\n")

        for idx, result in enumerate(results, 1):
            lines.append(f"### {idx}. {result.file_path.name}\n")

            # File info
            lines.append("**File Information:**")
            lines.append(f"- Path: `{result.file_path}`")
            lines.append(f"- Type: {result.file_type}")
            lines.append(f"- Analyzed: {result.timestamp.strftime('%Y-%m-%d %H:%M:%S')}")

            if include_metadata and result.metadata:
                lines.append(f"- Processing Time: {result.metadata.get('duration_ms', 0):.2f}ms")
                if "page" in result.metadata:
                    lines.append(f"- Page: {result.metadata['page']}")

            lines.append("")

            # Task
            lines.append("**Analysis Task:**")
            lines.append(f"> {result.task}\n")

            # Results
            lines.append("**Analysis Results:**\n")
            lines.append(result.text)
            lines.append("\n")

            # Separator
            if idx < len(results):
                lines.append("---\n")

        # Summary
        if kwargs.get("include_summary", True):
            lines.append("## Summary\n")
            lines.append(self._generate_summary(results))

        # Footer
        lines.append("\n---")
        lines.append(f"\n*Report generated by Vision Agent Analyst*")
        lines.append(f"\n*Model: {self.config.ollama_model}*")

        return "\n".join(lines)

    def _create_anchor(self, text: str, idx: int) -> str:
        """Create markdown anchor from text.

        Args:
            text: Text to create anchor from.
            idx: Index number.

        Returns:
            Anchor string.
        """
        # Simple anchor creation
        anchor = f"{idx}-{text}".lower()
        anchor = anchor.replace(" ", "-")
        anchor = "".join(c for c in anchor if c.isalnum() or c == "-")
        return anchor

    def _generate_summary(self, results: List[Any]) -> str:
        """Generate summary section.

        Args:
            results: List of AnalysisResult objects.

        Returns:
            Summary text.
        """
        lines = []

        # Count by type
        type_counts = {}
        total_time = 0

        for result in results:
            file_type = result.file_type
            type_counts[file_type] = type_counts.get(file_type, 0) + 1
            total_time += result.metadata.get("duration_ms", 0)

        lines.append(f"This report contains analysis of **{len(results)} files**:\n")

        for file_type, count in type_counts.items():
            lines.append(f"- {file_type.capitalize()}: {count} file(s)")

        lines.append(f"\nTotal processing time: **{total_time:.2f}ms** ({total_time/1000:.2f}s)")

        return "\n".join(lines)

    def generate_json(
        self,
        results: List[Any],
        output_path: Optional[Path] = None,
        **kwargs
    ) -> Path:
        """Generate JSON report.

        Args:
            results: List of AnalysisResult objects.
            output_path: Optional output path.
            **kwargs: Additional parameters.

        Returns:
            Path to the generated JSON file.
        """
        import json

        if output_path is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = self.config.output_dir / f"report_{timestamp}.json"
        else:
            output_path = Path(output_path)

        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Convert results to dictionaries
        data = {
            "metadata": {
                "generated": datetime.now().isoformat(),
                "model": self.config.ollama_model,
                "total_files": len(results),
            },
            "results": [result.to_dict() for result in results],
        }

        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

        logger.info(f"JSON report generated: {output_path}")
        return output_path

    def generate_pdf(
        self,
        results: List[Any],
        output_path: Optional[Path] = None,
        title: str = "Vision Agent Analysis Report",
        include_metadata: bool = True,
        **kwargs
    ) -> Path:
        """Generate PDF report.

        Args:
            results: List of AnalysisResult objects.
            output_path: Optional output path.
            title: Report title.
            include_metadata: Whether to include metadata.
            **kwargs: Additional parameters.

        Returns:
            Path to the generated PDF file.

        Raises:
            ImportError: If reportlab is not installed.
        """
        if not PDF_EXPORT_AVAILABLE:
            raise ImportError(
                "PDF export requires reportlab. "
                "Install it with: pip install reportlab"
            )

        if output_path is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = self.config.output_dir / f"report_{timestamp}.pdf"
        else:
            output_path = Path(output_path)

        exporter = PDFExporter()
        return exporter.export(
            results=results,
            output_path=output_path,
            title=title,
            include_metadata=include_metadata,
            **kwargs
        )

    def generate_pdf_bytes(
        self,
        results: List[Any],
        title: str = "Vision Agent Analysis Report",
        include_metadata: bool = True,
        **kwargs
    ) -> bytes:
        """Generate PDF report as bytes.

        Args:
            results: List of AnalysisResult objects.
            title: Report title.
            include_metadata: Whether to include metadata.
            **kwargs: Additional parameters.

        Returns:
            PDF content as bytes.

        Raises:
            ImportError: If reportlab is not installed.
        """
        if not PDF_EXPORT_AVAILABLE:
            raise ImportError(
                "PDF export requires reportlab. "
                "Install it with: pip install reportlab"
            )

        exporter = PDFExporter()
        return exporter.export_to_bytes(
            results=results,
            title=title,
            include_metadata=include_metadata,
            **kwargs
        )
